apiVersion: v1
kind: PersistentVolume
metadata:
  name: tensorflow-fs
  namespace: default
  labels:
    heritage: "Tiller"
    chart: "efs-0.0.1"
    release: "release-name"
  annotations:
    "helm.sh/created": "1490351799"
spec:
  capacity:
    storage: 900Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: "fs-f86dd8b1.efs.us-east-1.amazonaws.com"
    path: "/"

